# Generated by Django 6.0.6 on 2026-07-05 20:03

import django.db.models.deletion
import nftapp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NFT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator_name', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to=nftapp.models.nft_upload_path)),
                ('category', models.CharField(choices=[('art', 'Digital Art'), ('photography', 'Photography'), ('music', 'Music'), ('collectible', 'Collectible'), ('video', 'Video'), ('other', 'Other')], default='art', max_length=20)),
                ('price', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('token_id', models.CharField(editable=False, max_length=32, unique=True)),
                ('content_hash', models.CharField(blank=True, editable=False, max_length=64)),
                ('is_listed', models.BooleanField(default=True)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nfts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('nft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_set', to='nftapp.nft')),
            ],
            options={
                'unique_together': {('user', 'nft')},
            },
        ),
    ]
