# Generated by Django 5.2.16 on 2026-07-09 03:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nftapp', '0003_nft_burned_at_nft_is_burned_nft_is_lazy_minted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='nft',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_nfts', to=settings.AUTH_USER_MODEL),
        ),
    ]
