# Generated by Django 5.2.16 on 2026-07-09 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nftapp', '0004_nft_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='nft',
            name='currency',
            field=models.CharField(choices=[('ETH', 'ETH — Ethereum'), ('MNQ', 'MNQ — Mintique Token')], default='ETH', max_length=6),
        ),
    ]
