# Generated by Django 5.2.16 on 2026-07-13 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nftapp', '0005_nft_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nft',
            name='token_id',
            field=models.CharField(editable=False, max_length=36, unique=True),
        ),
    ]
