# Generated by Django 5.2.16 on 2026-07-13 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nftapp', '0006_alter_nft_token_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='nft',
            name='chain_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nft',
            name='contract_address',
            field=models.CharField(blank=True, max_length=42),
        ),
        migrations.AddField(
            model_name='nft',
            name='ipfs_image_cid',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='nft',
            name='ipfs_metadata_cid',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='nft',
            name='mint_status',
            field=models.CharField(choices=[('offchain', 'Off-chain (simulated)'), ('pending', 'Pending on-chain confirmation'), ('confirmed', 'Confirmed on Polygon')], default='offchain', max_length=12),
        ),
        migrations.AddField(
            model_name='nft',
            name='minter_wallet_address',
            field=models.CharField(blank=True, max_length=42),
        ),
        migrations.AddField(
            model_name='nft',
            name='onchain_token_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nft',
            name='polygon_tx_hash',
            field=models.CharField(blank=True, max_length=66),
        ),
    ]
