# Generated by Django 5.2.16 on 2026-07-13 03:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nftapp', '0007_nft_chain_id_nft_contract_address_nft_ipfs_image_cid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NFTAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trait_type', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=100)),
                ('nft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='nftapp.nft')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=12)),
                ('currency', models.CharField(choices=[('ETH', 'ETH — Ethereum'), ('MNQ', 'MNQ — Mintique Token')], default='ETH', max_length=6)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Declined'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=10)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers_made', to=settings.AUTH_USER_MODEL)),
                ('nft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='nftapp.nft')),
            ],
            options={
                'ordering': ['-amount', '-created_at'],
            },
        ),
    ]
