# Generated by Django 5.2.16 on 2026-07-14 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nftapp', '0008_nftattribute_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='nft',
            name='image_uri',
            field=models.CharField(blank=True, help_text='ipfs://<CID> of the pinned artwork.', max_length=255),
        ),
        migrations.AddField(
            model_name='nft',
            name='is_soulbound',
            field=models.BooleanField(default=False, help_text='ERC-5192 — if set, this token is non-transferable once minted.'),
        ),
        migrations.AddField(
            model_name='nft',
            name='metadata_uri',
            field=models.CharField(blank=True, help_text="ipfs://<CID> of the pinned ERC-721 metadata JSON — this is exactly what the contract's tokenURI(tokenId) resolves to.", max_length=255),
        ),
        migrations.AddField(
            model_name='nft',
            name='mint_error',
            field=models.CharField(blank=True, help_text='Last IPFS/on-chain error message, if mint_status is offchain/pending due to a failure.', max_length=255),
        ),
        migrations.AddField(
            model_name='nft',
            name='minted_at',
            field=models.DateTimeField(blank=True, help_text='When the mint transaction was confirmed on-chain (distinct from created_at, which is when the off-chain database row was first created).', null=True),
        ),
        migrations.AddField(
            model_name='nft',
            name='network',
            field=models.CharField(blank=True, choices=[('polygon-amoy', 'Polygon Amoy (testnet)'), ('polygon-mainnet', 'Polygon Mainnet')], help_text="Chain the mint was (or will be) confirmed on — set from settings.POLYGON_NETWORK at mint time so it stays accurate even if the site's active network later changes.", max_length=20),
        ),
        migrations.AddField(
            model_name='nft',
            name='standard_metadata',
            field=models.JSONField(blank=True, default=dict, help_text="Standard-specific extra state, e.g. {'rental_user': '0x..', 'rental_expires': ..} for ERC-4907, or {'supply': N} for ERC-1155."),
        ),
        migrations.AddField(
            model_name='nft',
            name='token_standard',
            field=models.CharField(choices=[('erc721', 'ERC-721 — single edition'), ('erc1155', 'ERC-1155 — multi-token / editions'), ('erc4907', 'ERC-4907 — rentable (extends ERC-721)'), ('erc5192', 'ERC-5192 — soulbound (extends ERC-721)')], default='erc721', help_text='Which token contract family this NFT is minted under. See TokenStandard for the extensibility rationale.', max_length=10),
        ),
        migrations.AlterField(
            model_name='nft',
            name='mint_status',
            field=models.CharField(choices=[('offchain', 'Off-chain (simulated)'), ('pending', 'Pending on-chain confirmation'), ('confirmed', 'Confirmed on Polygon'), ('failed', 'On-chain mint failed')], default='offchain', max_length=12),
        ),
    ]
