# Generated by Django 6.0.7 on 2026-07-25 20:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nftapp', '0009_nft_image_uri_nft_is_soulbound_nft_metadata_uri_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='nft',
            constraint=models.UniqueConstraint(condition=models.Q(('onchain_token_id__isnull', False)), fields=('contract_address', 'chain_id', 'onchain_token_id'), name='unique_onchain_token_per_contract_chain'),
        ),
        migrations.AddConstraint(
            model_name='nft',
            constraint=models.UniqueConstraint(condition=models.Q(('polygon_tx_hash', ''), _negated=True), fields=('polygon_tx_hash',), name='unique_polygon_tx_hash'),
        ),
    ]
