# Generated by Django 6.0.7 on 2026-07-26 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nftapp', '0010_nft_unique_onchain_token_per_contract_chain_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nft',
            name='token_id',
        ),
    ]
