# Generated by Django 6.0.6 on 2026-07-05 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_type', models.CharField(choices=[('mint', 'Mint'), ('buy', 'Buy'), ('sell', 'Sell'), ('swap', 'Swap'), ('connect', 'Wallet Connected')], max_length=10)),
                ('token', models.CharField(default='ETH', max_length=10)),
                ('amount', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('tx_hash', models.CharField(editable=False, max_length=66, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eth_balance', models.DecimalField(decimal_places=6, default=5, max_digits=18)),
                ('mnq_balance', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
