# Generated by Django 5.2.16 on 2026-07-09 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walletapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='tx_type',
            field=models.CharField(choices=[('mint', 'Mint'), ('buy', 'Buy'), ('sell', 'Sell'), ('swap', 'Swap'), ('connect', 'Wallet Connected'), ('gift', 'Gift'), ('burn', 'Burn')], max_length=10),
        ),
    ]
