# Generated by Django 5.2.16 on 2026-07-13 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nftapp', '0008_nftattribute_offer'),
        ('walletapp', '0004_wallet_multi_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='nft',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity', to='nftapp.nft'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tx_type',
            field=models.CharField(choices=[('mint', 'Mint'), ('buy', 'Buy'), ('sell', 'Sell'), ('swap', 'Swap'), ('connect', 'Wallet Connected'), ('gift', 'Gift'), ('burn', 'Burn'), ('royalty', 'Creator Royalty'), ('offer', 'Offer'), ('list', 'Listed')], max_length=10),
        ),
    ]
